name: Rotate Banner Daily

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:     # manual run

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all banner images safely
        id: list_banners
        run: |
          # Find all images in banners folder
          BANNERS=($(find banners -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \)))
          if [ ${#BANNERS[@]} -eq 0 ]; then
            echo "No banners found!"
            exit 1
          fi
          echo "Found banners: ${BANNERS[@]}"

          # Exclude current banner.png if it exists
          if [ -f banner.png ]; then
            CURRENT=$(basename banner.png)
            FILTERED=()
            for b in "${BANNERS[@]}"; do
              if [ "$(basename $b)" != "$CURRENT" ]; then
                FILTERED+=("$b")
              fi
            done
            BANNERS=("${FILTERED[@]}")
          fi

          # Pick a random banner
          RANDOM_INDEX=$(( RANDOM % ${#BANNERS[@]} ))
          SELECTED=${BANNERS[$RANDOM_INDEX]}
          echo "Selected banner: $SELECTED"
          echo "banner=$SELECTED" >> $GITHUB_ENV

      - name: Copy selected banner
        run: |
          cp "$banner" banner.png

      - name: Commit & push updated banner
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add banner.png
          git diff --cached --exit-code || git commit -m "Rotate banner image"
          git push || echo "No changes to commit"
